# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to `NumPy’s ndarrays`, except that **tensors can run on GPUs or other specialized hardware to accelerate computing**.

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
## from a numpy array 
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
# from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3143, 0.0514],
        [0.3789, 0.4124]]) 



In [5]:
## with random or constant value
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1143, 0.4551, 0.7334],
        [0.2880, 0.6109, 0.7191]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
torch.empty(2, 2)          # uninitialized memory — garbage values, fast

tensor([[-4.3019e-22,  1.2107e-42],
        [ 0.0000e+00,  0.0000e+00]])

In [7]:
torch.eye(3)               # identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [8]:
torch.full((2, 2), 7)      # filled with a specific value

tensor([[7, 7],
        [7, 7]])

In [9]:
# Random
torch.rand(2, 3)           # uniform [0, 1)

tensor([[0.9578, 0.5820, 0.6714],
        [0.0441, 0.4453, 0.6637]])

In [10]:
torch.randn(2, 3)          # standard normal

tensor([[ 0.2367,  0.8120,  0.7483],
        [-0.5660, -1.9765,  1.1931]])

In [11]:
torch.randint(0, 10, (2, 3))  # random ints in range

tensor([[1, 8, 3],
        [8, 4, 9]])

In [12]:
a = torch.tensor([1., 2., 3.])    

In [13]:
# Ranges
torch.arange(0, 10, 2)     # like Python range: start, end, step
torch.linspace(0, 1, 5)    # 5 evenly spaced points from 0 to 1

# "Like" variants — match shape/dtype/device of another tensor
torch.zeros_like(a)
torch.ones_like(a)
torch.rand_like(a.float())  # rand_like requires float dtype

tensor([0.2813, 0.0316, 0.6490])

In [14]:
x = torch.tensor([1, 2, 3], dtype=torch.float32, device='cpu')
x = torch.randn(3, 3, dtype=torch.float64)

# Common dtypes
torch.float32   # default float, aka torch.float
torch.float16   # half precision
torch.bfloat16  # used heavily in modern LLM training
torch.int64     # default int, aka torch.long — required for indexing/labels
torch.bool

torch.bool

## Tensor Attributes

In [15]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Tensor Operations

In [16]:
# We move our tensor to the GPU if available
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
tensor = tensor.to(device)
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [17]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [18]:
## Joining Tensor: concat: Concatenation along a dimension
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [19]:
### Element wise operations

tensor + tensor

tensor([[2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.],
        [2., 0., 2., 2.]])

In [20]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [22]:
tensor ** 2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [23]:
torch.exp(tensor)

tensor([[2.7183, 1.0000, 2.7183, 2.7183],
        [2.7183, 1.0000, 2.7183, 2.7183],
        [2.7183, 1.0000, 2.7183, 2.7183],
        [2.7183, 1.0000, 2.7183, 2.7183]])

In [24]:
# In-place operations Operations that have a _ suffix are in-place. For example: x.copy_(y), x.t_(), will change x.
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [25]:
torch.sqrt(tensor)

tensor([[2.4495, 2.2361, 2.4495, 2.4495],
        [2.4495, 2.2361, 2.4495, 2.4495],
        [2.4495, 2.2361, 2.4495, 2.4495],
        [2.4495, 2.2361, 2.4495, 2.4495]])

In [26]:
torch.relu(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [27]:
# Reduction (shape shrinks — collapses a dimension or the whole tensor)
a.sum(), a.mean(), a.max(), a.sum(dim=0), a.sum(dim=-1, keepdim=True)

(tensor(6.), tensor(2.), tensor(3.), tensor(6.), tensor([6.]))

In [28]:
x = torch.randn(4, 3)
x

tensor([[-0.3536, -1.6303, -0.0570],
        [ 0.4141,  0.6144,  1.5835],
        [ 0.0078, -0.5081,  1.2646],
        [-0.1402,  0.7924, -0.0025]])

In [29]:
x.sum(dim=0)

tensor([-0.0719, -0.7316,  2.7885])

In [30]:
x.sum(dim=-1)

tensor([-2.0409,  2.6120,  0.7643,  0.6496])

In [31]:
a = torch.randn(2, 3)
b = torch.randn(3, 5)
c = a @ b
print(c.shape)  # (2, 5)

# Now deliberately break it
d = torch.randn(4, 5)
try:
    a @ d
except Exception as e:
    print(e)  # read the exact shape mismatch message

torch.Size([2, 5])
mat1 and mat2 shapes cannot be multiplied (2x3 and 4x5)


#### In-place vs. out-of-place ops (naming convention)

Any method ending in _ mutates in place: `.add_()`, `.mul_()`, `.relu_()`, `.zero_()`. No underscore = returns a new tensor.

In [32]:
x = torch.tensor([1., 2., 3.])
y = x.add(1)     # new tensor, x unchanged
x.add_(1)        # x itself changed

tensor([2., 3., 4.])

**Rule of thumb**: avoid in-place ops on tensors that are part of an autograd graph unless you know exactly why (see the earlier autograd section — it can break gradient computation).

In [33]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 2, 2])
a == b        # tensor([False, True, False])
a > b         # elementwise bool tensor
torch.equal(a, b)   # single Python bool — True only if ALL elements match
(a == b).all()      # tensor(False) — as a tensor, not a Python bool
(a == b).any()      # tensor(True)

tensor(True)

In [34]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([1.0, 2.0000001, 3.0])
print(x == y)              # False in position 1 — floats rarely match exactly
print(torch.allclose(x, y))  # True — this is what you should use for float comparison

tensor([True, True, True])
True


In [35]:
x = torch.randn(3, 4, requires_grad=True)

x.shape          # torch.Size([3, 4])
x.size()         # same thing, callable form
x.dtype          # torch.float32
x.device         # device('cpu')
x.requires_grad  # True
x.grad_fn        # None (it's a leaf) or <SomeBackward>
x.is_leaf        # True
x.ndim           # 2 — number of dimensions
x.numel()        # 12 — total number of elements
x.is_contiguous()  # True
x.stride()       # (4, 1)
x.storage().data_ptr()  # memory address — check if two tensors share storage

C:\Users\user\AppData\Local\Temp\ipykernel_4996\97171217.py:14: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage().data_ptr()  # memory address — check if two tensors share storage


3713469189952

In [36]:
def inspect(t, name="tensor"):
    print(f"{name}: shape={tuple(t.shape)}, dtype={t.dtype}, device={t.device}, "
          f"requires_grad={t.requires_grad}, contiguous={t.is_contiguous()}")

x = torch.randn(2, 3, requires_grad=True)
inspect(x, "x")

x: shape=(2, 3), dtype=torch.float32, device=cpu, requires_grad=True, contiguous=True


### Part3: `nn.Parameter`
3.1 What makes a `Parameter` different from a regular tensor
`nn.Parameter` is just a `torch.Tensor` subclass with two behavioral differences:

1. `requires_grad=True` by default
2. When assigned as an attribute of an `nn.Module`, it's automatically registered — it shows up in `.parameters()` and gets saved in `.state_dict()`

In [37]:
import torch.nn as nn

class Tiny(nn.Module):
    def __init__(self):
        super().__init__()
        self.w = nn.Parameter(torch.randn(3, 3))  # tracked
        self.plain = torch.randn(3, 3)             # NOT tracked, invisible to optimizer

m = Tiny()
print(list(m.parameters()))  # only w shows up

[Parameter containing:
tensor([[ 0.9026, -1.7115,  0.1444],
        [ 0.1404,  0.8699,  0.1627],
        [ 1.4126, -0.4553, -1.9871]], requires_grad=True)]


In [38]:
class Buggy(nn.Module):
    def __init__(self):
        super().__init__()
        self.weight = torch.randn(4, 4, requires_grad=True)  # looks fine, but WRONG

m = Buggy()
print(list(m.parameters()))  # empty! optimizer will never update this weight

[]


In [43]:
## Registering Parameters manually

class Manual(nn.Module):
    def __init__(self):
        super().__init__()

        self.register_buffer('w', nn.Parameter(torch.randn(3)))

test = Manual()

In [44]:
list(test.parameters())

[]

In [46]:
test.state_dict().keys()

odict_keys(['w'])

In [47]:
import torch.nn.functional as F

class MyLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(out_features, in_features))
        self.bias = nn.Parameter(torch.randn(out_features))

    def forward(self, x):
        return x @ self.weight.T + self.bias

x = torch.randn(5, 3)  # batch of 5, 3 features each

my_lin = MyLinear(3, 2)
real_lin = nn.Linear(3, 2)

# Copy weights so we can compare apples to apples
with torch.no_grad():
    real_lin.weight.copy_(my_lin.weight)
    real_lin.bias.copy_(my_lin.bias)

out1 = my_lin(x)
out2 = real_lin(x)
print(torch.allclose(out1, out2))  # should be True

True


In [48]:
x = torch.arange(24).view(2, 3, 4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [49]:
x.view(2, 3, 2, 2)

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]])

In [50]:
import torch

b, t, n_heads, d_k = 2, 4, 3, 5
d_model = n_heads * d_k

Q = torch.arange(b * t * d_model).float().view(b, t, d_model)
print("Before:", Q.shape)  # (2, 4, 15)

Q2 = Q.view(b, t, n_heads, d_k)
print("After view:", Q2.shape)  # (2, 4, 3, 5)

Q3 = Q2.transpose(1, 2)
print("After transpose:", Q3.shape)  # (2, 3, 4, 5)

print("Is Q3 contiguous?", Q3.is_contiguous())  # False

Before: torch.Size([2, 4, 15])
After view: torch.Size([2, 4, 3, 5])
After transpose: torch.Size([2, 3, 4, 5])
Is Q3 contiguous? False


In [51]:
if torch.accelerator.is_available():
    gpu_rand = torch.rand(2, 2, device=torch.accelerator.current_accelerator())
    print(gpu_rand)
else:
    print("Sorry, CPU only.")

Sorry, CPU only.


In [52]:
my_device = (
    torch.accelerator.current_accelerator()
    if torch.accelerator.is_available()
    else torch.device("cpu")
)
print(f"Device: {my_device}")

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.3525, 0.8176],
        [0.4568, 0.9074]])


## Building Models in PyTorch


#### `torch.nn.Module` and `torch.nn.Parameter`

In this video, we'll be discussing some of the tools PyTorch makes available for building deep learning networks.

Except for `Parameter`, the classes we discuss in this video are all subclasses of `torch.nn.Module`. This is the PyTorch base class meant to encapsulate behaviors specific to PyTorch Models and their components.

One important behavior of `torch.nn.Module` is registering parameters. If a particular `Module` subclass has learning weights, these weights are expressed as instances of `torch.nn.Parameter`. The `Parameter` class is a subclass of `torch.Tensor`, with the special behavior that when they are assigned as attributes of a `Module`, they are added to the list of that modules parameters. These parameters may be accessed through the `parameters()` method on the `Module` class.

As a simple example, here's a very simple model with two linear layers and an activation function. We'll create an instance of it and ask it to report on its parameters:

In [1]:
import torch

class TinyModel(torch.nn.Module):
    
    def __init__(self):
        super(TinyModel, self).__init__()
        
        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()
    
    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

print('The model:')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[ 0.0879,  0.0195, -0.0143,  ...,  0.0635, -0.0894, -0.0015],
        [-0.0896,  0.0130, -0.0597,  ...,  0.0577, -0.0085,  0.0207],
        [ 0.0348, -0.0421, -0.0045,  ...,  0.0529,  0.0756,  0.0741],
        ...,
        [ 0.0885, -0.0530, -0.0419,  ...,  0.0062, -0.0335, -0.0045],
        [-0.0349,  0.0399, -0.0248,  ...,  0.0638,  0.0452, -0.0558],
        [ 0.0412, -0.0588,  0.0331,  ...,  0.0139,  0.0619,  0.0666]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0289, -0.0811, -0.0516,  0.0886,  0.0685, -0.0975,  0.0238,  0.0050,
        -0.0786,  0.0509, -0.0743, -0.0589, -0.0767, -0.0583, -0.0151,  0.0184,
        -0.0814,  0.0100, -0.0261,  0.03

In [5]:
print(list(tinymodel.parameters()))

[Parameter containing:
tensor([[ 0.0879,  0.0195, -0.0143,  ...,  0.0635, -0.0894, -0.0015],
        [-0.0896,  0.0130, -0.0597,  ...,  0.0577, -0.0085,  0.0207],
        [ 0.0348, -0.0421, -0.0045,  ...,  0.0529,  0.0756,  0.0741],
        ...,
        [ 0.0885, -0.0530, -0.0419,  ...,  0.0062, -0.0335, -0.0045],
        [-0.0349,  0.0399, -0.0248,  ...,  0.0638,  0.0452, -0.0558],
        [ 0.0412, -0.0588,  0.0331,  ...,  0.0139,  0.0619,  0.0666]],
       requires_grad=True), Parameter containing:
tensor([ 0.0289, -0.0811, -0.0516,  0.0886,  0.0685, -0.0975,  0.0238,  0.0050,
        -0.0786,  0.0509, -0.0743, -0.0589, -0.0767, -0.0583, -0.0151,  0.0184,
        -0.0814,  0.0100, -0.0261,  0.0378,  0.0909, -0.0679,  0.0338,  0.0913,
        -0.0374, -0.0082, -0.0838, -0.0426,  0.0742,  0.0426, -0.0576, -0.0369,
         0.0351, -0.0151, -0.0963, -0.0163, -0.0974, -0.0942, -0.0276,  0.0601,
         0.0556,  0.0526,  0.0580, -0.0451,  0.0667, -0.0709,  0.0447,  0.0808,
         0.03

This shows the fundamental structure of a PyTorch model: there is an `__init__()` method that defines the layers and other components of a model, and a `forward()` method where the computation gets done. Note that we can print the model, or any of its submodules, to learn about its structure.

## Common Layer Types

### Linear Layers

The most basic type of neural network layer is a *linear* or *fully connected* layer. This is a layer where every input influences every output of the layer to a degree specified by the layer's weights. If a model has *m* inputs and *n* outputs, the weights will be an *m * n* matrix. For example:

In [6]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\nOutput:')
print(y)

Input:
tensor([[0.2956, 0.8073, 0.9074]])


Weight and Bias parameters:
Parameter containing:
tensor([[-0.1345, -0.2375,  0.3588],
        [ 0.4330, -0.4307, -0.5378]], requires_grad=True)
Parameter containing:
tensor([-0.4439,  0.4608], requires_grad=True)


Output:
tensor([[-0.3497, -0.2469]], grad_fn=<AddmmBackward0>)


If you do the matrix multiplication of `x` by the linear layer's weights, and add the biases, you'll find that you get the output vector `y`.

One other important feature to note: When we checked the weights of our layer with `lin.weight`, it reported itself as a `Parameter` (which is a subclass of `Tensor`), and let us know that it's tracking gradients with autograd. This is a default behavior for `Parameter` that differs from `Tensor`.

Linear layers are used widely in deep learning models. One of the most common places you'll see them is in classifier models, which will usually have one or more linear layers at the end, where the last layer will have *n* outputs, where *n* is the number of classes the classifier addresses.

### Convolutional Layers

*Convolutional* layers are built to handle data with a high degree of spatial correlation. They are very commonly used in computer vision, where they detect close groupings of features which the compose into higher-level features. They pop up in other contexts too - for example, in NLP applications, where the a word's immediate context (that is, the other words nearby in the sequence) can affect the meaning of a sentence.

We saw convolutional layers in action in LeNet5 in an earlier video:

In [7]:
import torch.functional as F


class LeNet(torch.nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = torch.nn.Conv2d(1, 6, 5)
        self.conv2 = torch.nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = torch.nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

Let's break down what's happening in the convolutional layers of this model. Starting with `conv1`:

* LeNet5 is meant to take in a 1x32x32 black & white image. **The first argument to a convolutional layer's constructor is the number of input channels.** Here, it is 1. If we were building this model to look at 3-color channels, it would be 3.
* A convolutional layer is like a window that scans over the image, looking for a pattern it recognizes. These patterns are called *features,* and one of the parameters of a convolutional layer is the number of features we would like it to learn. **This is the second argument to the constructor is the number of output features.** Here, we're asking our layer to learn 6 features.
* Just above, I likened the convolutional layer to a window - but how big is the window? **The third argument is the window or *kernel* size.** Here, the "5" means we've chosen a 5x5 kernel. (If you want a kernel with height different from width, you can specify a tuple for this argument - e.g., `(3, 5)` to get a 3x5 convolution kernel.)

The output of a convolutional layer is an *activation map* - a spatial representation of the presence of features in the input tensor. `conv1` will give us an output tensor of 6x28x28; 6 is the number of features, and 28 is the height and width of our map. (The 28 comes from the fact that when scanning a 5-pixel window over a 32-pixel row, there are only 28 valid positions.)

We then pass the output of the convolution through a ReLU activation function (more on activation functions later), then through a max pooling layer. The max pooling layer takes features near each other in the activation map and groups them together. It does this by reducing the tensor, merging every 2x2 group of cells in the output into a single cell, and assigning that cell the maximum value of the 4 cells that went into it. This gives us a lower-resolution version of the activation map, with dimensions 6x14x14.

Our next convolutional layer, `conv2`, expects 6 input channels (corresponding to the 6 features sought by the first layer), has 16 output channels, and a 3x3 kernel. It puts out a 16x12x12 activation map, which is again reduced by a max pooling layer to 16x6x6. Prior to passing this output to the linear layers, it is reshaped to a 16 * 6 * 6 = 576-element vector for consumption by the next layer.

There are convolutional layers for addressing 1D, 2D, and 3D tensors. There are also many more optional arguments for a conv layer constructor, including stride length(e.g., only scanning every second or every third position) in the input, padding (so you can scan out to the edges of the input), and more. See the [documentation](https://pytorch.org/docs/stable/nn.html#convolution-layers) for more information.

### Recurrent Layers

*Recurrent neural networks* (or *RNNs)* are used for sequential data - anything from time-series measurements from a scientific instrument to natural language sentences to DNA nucleotides. An RNN does this by maintaining a *hidden state* that acts as a sort of memory for what it has seen in the sequence so far.

The internal structure of an RNN layer - or its variants, the LSTM (long short-term memory) and GRU (gated recurrent unit) - is moderately complex and beyond the scope of this video, but we'll show you what one looks like in action with an LSTM-based part-of-speech tagger (a type of classifier that tells you if a word is a noun, verb, etc.):

In [8]:
class LSTMTagger(torch.nn.Module):

    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim

        self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)

        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim)

        # The linear layer that maps from hidden state space to tag space
        self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores

The constructor has four arguments:

* `vocab_size` is the number of words in the input vocabulary. Each word is a one-hot vector (or unit vector) in a `vocab_size`-dimensional space.
* `tagset_size` is the number of tags in the output set.
* `embedding_dim` is the size of the *embedding* space for the vocabulary. An embedding maps a vocabulary onto a low-dimensional space, where words with similar meanings are close together in the space.
* `hidden_dim` is the size of the LSTM's memory.

The input will be a sentence with the words represented as indices of of one-hot vectors. The embedding layer will then map these down to an `embedding_dim`-dimensional space. The LSTM takes this sequence of embeddings and iterates over it, fielding an output vector of length `hidden_dim`. The final linear layer acts as a classifier; applying `log_softmax()` to the output of the final layer converts the output into a normalized set of estimated probabilities that a given word maps to a given tag.

If you'd like to see this network in action, check out the [Sequence Models and LSTM Networks](https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html) tutorial on pytorch.org.

### Transformers

*Transformers* are multi-purpose networks that have taken over the state of the art in NLP with models like BERT. A discussion of transformer architecture is beyond the scope of this video, but PyTorch has a `Transformer` class that allows you to define the overall parameters of a transformer model - the number of attention heads, the number of encoder & decoder layers, dropout and activation functions, etc. (You can even build the BERT model from this single class, with the right parameters!) The `torch.nn.Transformer` class also has classes to encapsulate the individual components (`TransformerEncoder`, `TransformerDecoder`) and subcomponents (`TransformerEncoderLayer`, `TransformerDecoderLayer`). For details, check out the [documentation](https://pytorch.org/docs/stable/nn.html#transformer) on transformer classes, and the relevant [tutorial](https://pytorch.org/tutorials/beginner/transformer_tutorial.html) on pytorch.org.

## Other Layers and Functions

### Data Manipulation Layers

There are other layer types that perform important functions in models, but don't participate in the learning process themselves.

**Max pooling** (and its twin, min pooling) reduce a tensor by combining cells, and assigning the maximum value of the input cells to the output cell. (We saw this ) For example:

In [9]:
my_tensor = torch.rand(1, 6, 6)
print(my_tensor)

maxpool_layer = torch.nn.MaxPool2d(3)
print(maxpool_layer(my_tensor))

tensor([[[0.2518, 0.4381, 0.1970, 0.3556, 0.7612, 0.8557],
         [0.3214, 0.9537, 0.3785, 0.8214, 0.6318, 0.0245],
         [0.4224, 0.2699, 0.1772, 0.6358, 0.9614, 0.0583],
         [0.5367, 0.3762, 0.8059, 0.1483, 0.1474, 0.9930],
         [0.2540, 0.8885, 0.4219, 0.3956, 0.0993, 0.3082],
         [0.9164, 0.5841, 0.7282, 0.9679, 0.7437, 0.9401]]])
tensor([[[0.9537, 0.9614],
         [0.9164, 0.9930]]])


If you look closely at the values above, you'll see that each of the values in the maxpooled output is the maximum value of each quadrant of the 6x6 input.

**Normalization layers** re-center and normalize the output of one layer before feeding it to another. Centering the and scaling the intermediate tensors has a number of beneficial effects, such as letting you use higher learning rates without exploding/vanishing gradients.

In [10]:
my_tensor = torch.rand(1, 4, 4) * 20 + 5
print(my_tensor)

print(my_tensor.mean())

norm_layer = torch.nn.BatchNorm1d(4)
normed_tensor = norm_layer(my_tensor)
print(normed_tensor)

print(normed_tensor.mean())


tensor([[[13.5104, 16.7494,  7.9628, 17.1344],
         [10.2981,  9.0069, 19.1398,  8.8326],
         [10.7682, 20.3572, 19.3937, 17.1015],
         [11.2313,  9.7453, 12.7650,  6.7033]]])
tensor(13.1687)
tensor([[[-0.0895,  0.7923, -1.5998,  0.8971],
         [-0.3568, -0.6596,  1.7167, -0.7004],
         [-1.6430,  0.9242,  0.6662,  0.0526],
         [ 0.5004, -0.1635,  1.1855, -1.5224]]],
       grad_fn=<NativeBatchNormBackward0>)
tensor(4.4703e-08, grad_fn=<MeanBackward0>)


Running the cell above, we've added a large scaling factor and offset to an input tensor; you should see the input tensor's `mean()` somewhere in the neighborhood of 15. After running it through the normalization layer, you can see that the values are smaller, and grouped around zero - in fact, the mean should be very small (> 1e-8).

This is beneficial because many activation functions (discussed below) have their strongest gradients near 0, but sometimes suffer from vanishing or exploding gradients for inputs that drive them far away from zero. Keeping the data centered around the area of steepest gradient will tend to mean faster, better learning and higher feasible learning rates.

**Dropout layers** are a tool for encouraging *sparse representations* in your model - that is, pushing it to do inference with less data.

Dropout layers work by randomly setting parts of the input tensor *during training* - dropout layers are always turned off for inference. This forces the model to learn against this masked or reduced dataset. For example:

In [11]:
my_tensor = torch.rand(1, 4, 4)

dropout = torch.nn.Dropout(p=0.4)
print(dropout(my_tensor))
print(dropout(my_tensor))

tensor([[[0.2613, 0.0000, 0.4296, 1.2452],
         [1.3422, 0.0000, 1.3240, 0.0000],
         [1.2405, 0.0000, 0.0000, 0.5805],
         [1.2701, 0.3653, 0.0000, 0.0000]]])
tensor([[[0.0000, 0.0000, 0.4296, 1.2452],
         [1.3422, 0.3359, 1.3240, 0.0000],
         [1.2405, 0.0000, 0.7501, 0.5805],
         [1.2701, 0.3653, 0.0000, 0.0000]]])


Above, you can see the effect of dropout on a sample tensor. You can use the optional `p` argument to set the probability of an individual weight dropping out; if you don't it defaults to 0.5.

### Activation Functions

Activation functions make deep learning possible. A neural network is really a program - with many parameters - that *simulates a mathematical function*. If all we did was multiple tensors by layer weights repeatedly, we could only simulate *linear functions;* further, there would be no point to having many layers, as the whole network would reduce could be reduced to a single matrix multiplication. Inserting *non-linear* activation functions between layers is what allows a deep learning model to simulate any function, rather than just linear ones.

`torch.nn.Module` has objects encapsulating all of the major activation functions including ReLU and its many variants, Tanh, Hardtanh, sigmoid, and more. It also includes other functions, such as Softmax, that are most useful at the output stage of a model.

### Loss Functions

Loss functions tell us how far a model's prediction is from the correct answer. PyTorch contains a variety of loss functions, including common MSE (mean squared error = L2 norm), Cross Entropy Loss and Negative Likelihood Loss (useful for classifiers), and others.

### The internal of `nn.Module`

In [1]:
from autograd import Tensor

In [2]:
class MyParameter:
    """Marker wrapper — anything wrapped in this is 'trainable' and should
    be picked up by __setattr__ and registered in _parameters."""
    def __init__(self, tensor):
        assert isinstance(tensor, Tensor), "MyParameter must wrap a Tensor"
        tensor.requires_grad = True
        self.tensor = tensor

    def __repr__(self):
        return f"MyParameter({self.tensor})"


class MyModule:
    def __init__(self):
        # These MUST exist before any attribute assignment happens,
        # since __setattr__ below checks against them on every assignment.
        object.__setattr__(self, '_parameters', {})
        object.__setattr__(self, '_modules', {})
        object.__setattr__(self, 'training', True)

    def __setattr__(self, name, value):
        # Intercept every attribute assignment on self.
        if isinstance(value, MyParameter):
            self._parameters[name] = value
        elif isinstance(value, MyModule):
            self._modules[name] = value
        else:
            object.__setattr__(self, name, value)

    def __getattr__(self, name):
        # Only called when normal attribute lookup FAILS — i.e. the name
        # isn't a real instance attribute, so check our registries.
        if name in self.__dict__.get('_parameters', {}):
            return self._parameters[name].tensor
        if name in self.__dict__.get('_modules', {}):
            return self._modules[name]
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

    def parameters(self):
        # Yield this module's own parameters...
        for p in self._parameters.values():
            yield p.tensor
        # ...then recurse into every submodule and yield theirs too.
        for module in self._modules.values():
            yield from module.parameters()

    def named_parameters(self, prefix=""):
        for name, p in self._parameters.items():
            full_name = f"{prefix}{name}"
            yield full_name, p.tensor
        for name, module in self._modules.items():
            yield from module.named_parameters(prefix=f"{prefix}{name}.")

    def train(self):
        self.training = True
        for module in self._modules.values():
            module.train()
        return self

    def eval(self):
        self.training = False
        for module in self._modules.values():
            module.eval()
        return self

    def __call__(self, *args, **kwargs):
        return self.forward(*args, **kwargs)

    def forward(self, *args, **kwargs):
        raise NotImplementedError("Subclasses must implement forward()")

In [3]:
import random

class MyLinear(MyModule):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = MyParameter(Tensor(
            [[random.uniform(-1, 1) for _ in range(in_features)] for _ in range(out_features)]
        ))
        self.bias = MyParameter(Tensor([0.0 for _ in range(out_features)]))

    def forward(self, x):
        # not implementing real matmul here — just enough to prove the
        # registration/recursion machinery works
        return x


class Block(MyModule):
    def __init__(self):
        super().__init__()
        self.fc1 = MyLinear(4, 4)
        self.fc2 = MyLinear(4, 4)


class Net(MyModule):
    def __init__(self):
        super().__init__()
        self.block1 = Block()
        self.block2 = Block()

In [4]:
net = Net()

params = list(net.parameters())
print(len(params))   # 8 — 2 params (weight+bias) x 2 Linears x 2 Blocks

for name, p in net.named_parameters():
    print(name)
# block1.fc1.weight
# block1.fc1.bias
# block1.fc2.weight
# block1.fc2.bias
# block2.fc1.weight
# block2.fc1.bias
# block2.fc2.weight
# block2.fc2.bias

print(net.training)          # True
net.eval()
print(net.training, net.block1.training, net.block1.fc1.training)  # False False Fals

8
block1.fc1.weight
block1.fc1.bias
block1.fc2.weight
block1.fc2.bias
block2.fc1.weight
block2.fc1.bias
block2.fc2.weight
block2.fc2.bias
True
False False False


### Dataset, DataLoader, and TensorDataset

**The core abstraction:** Dataset **is just "how to get one item"**

`torch.utils.data.Dataset` is deliberately minimal — a subclass just needs two methods:

```python
class MyDataset(torch.utils.data.Dataset):
    def __len__(self):
        return ...          # total number of samples
    def __getitem__(self, idx):
        return ...          # return ONE sample (and its label, typically as a tuple)
```

In [5]:
import torch
from torch.utils.data import Dataset, DataLoader

class ToyDataset(Dataset):
    def __init__(self, n=10):
        self.data = torch.arange(n).float()
        self.labels = torch.arange(n) % 2   # alternating 0/1

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

ds = ToyDataset()
print(len(ds))        # 10
print(ds[3])           # (tensor(3.), tensor(1))

10
(tensor(3.), tensor(1))
